<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ec99e6c0-2bdc-4a7d-85e8-2b338d09e55b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.autoCompleteCover > div > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f9c96a64-3c83-450c-836f-917aa46440ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../css/images/closeDark.png</value>
      <webElementGuid>07091638-a548-4b63-9d9a-a54652028c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;autoCompleteCover&quot;]/div[1]/img[1]</value>
      <webElementGuid>1dd2d991-3787-49f2-a462-cefb92698da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/img</value>
      <webElementGuid>af049ff7-2a99-47fb-a2c3-96758ce4e1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>f4b4c354-6a24-411a-8a2e-f111c6b890e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../css/images/closeDark.png']</value>
      <webElementGuid>bba7d964-14a8-4da4-a1db-dda0bca82d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
