<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign out_autoComplete</name>
   <tag></tag>
   <elementGuidId>252bcd2e-f14c-4454-9ebb-0c4dc48830fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autoComplete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#autoComplete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21557428-ae02-4908-ab82-ca260421be1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autoComplete</value>
      <webElementGuid>eb08574d-6c67-4f35-ab08-898f59848d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78920a8c-dd79-4da3-9de7-339ca41a9f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-regular ng-pristine ng-untouched ng-valid ng-dirty-add ng-valid-parse-add ng-animate ng-pristine-remove</value>
      <webElementGuid>572aaf1c-75af-4c20-bcfa-d97a4a227c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search AdvantageOnlineShopping.com</value>
      <webElementGuid>b7f9a5ba-c2f7-4898-819e-80210bbfb06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>checkEnterKey($event)</value>
      <webElementGuid>87a8e615-542d-45e5-af50-7ccd4988d04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>autoCompleteValue</value>
      <webElementGuid>7b56acc4-fe66-4666-8c6c-3fbdb515d799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keyup</name>
      <type>Main</type>
      <value>runAutocomplete()</value>
      <webElementGuid>d7a063c3-890e-4a60-a6a7-cab30c2b7b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f85d32c1-7249-4722-8253-1305b1d6d359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autoComplete&quot;)</value>
      <webElementGuid>d7b30740-1f23-4a1a-b47d-b02d3e73f724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autoComplete']</value>
      <webElementGuid>048896b7-edf0-400f-ac78-4d90933b065b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/input</value>
      <webElementGuid>edab7bcc-748c-4292-9c6a-ad3dd3b9548b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>9d528d58-0c92-434e-8ac1-5956e67c4d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'autoComplete' and @type = 'text' and @placeholder = 'Search AdvantageOnlineShopping.com']</value>
      <webElementGuid>f7e2d6b1-99d0-42bd-ac3d-054e21c7fe4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
